<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
    <parent>
        <groupId>cn.iocoder.cloud</groupId>
        <artifactId>yudao</artifactId>
        <version>${revision}</version>
    </parent>
    <modelVersion>4.0.0</modelVersion>
    <modules>
        <module>yudao-module-gift-api</module>
        <module>yudao-module-gift-server</module>
    </modules>
    <artifactId>yudao-module-gift</artifactId>
    <packaging>pom</packaging>

    <name>${project.artifactId}</name>
    <description>
        gift 模块，主要提供两块能力：
        1. 做任务
        2. 积分获取，兑换
    </description>

</project>
