-- 用户生成行程结构化存储。
-- gift_itinerary / gift_itinerary_item 继续用于公共线路模板，不与用户生成行程混用。
-- 本脚本只需执行一次；执行前请先确认 gift_user_itinerary 已由业务表脚本创建。

ALTER TABLE `gift_user_itinerary`
  COMMENT = '用户行程',
  MODIFY COLUMN `cover_url` varchar(1024) NOT NULL DEFAULT '' COMMENT '封面图',
  MODIFY COLUMN `cover_height` int NOT NULL DEFAULT 0 COMMENT '封面高度',
  MODIFY COLUMN `city_id` int DEFAULT NULL COMMENT '首个目的地城市ID',
  MODIFY COLUMN `next_city_id` int DEFAULT NULL COMMENT '下一目的地城市ID',
  MODIFY COLUMN `end_date` date DEFAULT NULL COMMENT '结束日期',
  ADD COLUMN `trip_id` bigint DEFAULT NULL COMMENT '旅行规划ID，对应 gift_trip_plan.id' AFTER `member_id`,
  ADD COLUMN `trip_itinerary_id` bigint DEFAULT NULL COMMENT '行程版本ID，对应 gift_trip_itinerary.id' AFTER `trip_id`,
  ADD COLUMN `conversation_id` bigint DEFAULT NULL COMMENT 'AI 会话ID' AFTER `trip_itinerary_id`,
  ADD COLUMN `message_id` bigint DEFAULT NULL COMMENT '行程对应的助手消息ID' AFTER `conversation_id`,
  ADD COLUMN `version` int NOT NULL DEFAULT 1 COMMENT '同一旅行规划内的版本号' AFTER `message_id`,
  ADD COLUMN `status` tinyint NOT NULL DEFAULT 1 COMMENT '行程版本状态，与 gift_trip_itinerary.status 一致' AFTER `version`,
  ADD COLUMN `departure` varchar(128) DEFAULT NULL COMMENT '出发地名称' AFTER `preference`,
  ADD COLUMN `destination` varchar(128) DEFAULT NULL COMMENT '目的地名称' AFTER `departure`,
  ADD COLUMN `traveler_count` int DEFAULT NULL COMMENT '出行人数' AFTER `destination`,
  ADD COLUMN `budget` int DEFAULT NULL COMMENT '总预算，单位元；不含往返交通' AFTER `traveler_count`,
  ADD COLUMN `hotel_budget` int DEFAULT NULL COMMENT '每晚住宿预算，单位元' AFTER `budget`,
  ADD COLUMN `traveler_profile_json` text DEFAULT NULL COMMENT '同行人构成 JSON' AFTER `hotel_budget`,
  ADD COLUMN `interests_json` text DEFAULT NULL COMMENT '旅行偏好 JSON 数组' AFTER `traveler_profile_json`,
  ADD COLUMN `pace` varchar(32) DEFAULT NULL COMMENT '行程节奏' AFTER `interests_json`,
  ADD COLUMN `must_visit_json` text DEFAULT NULL COMMENT '必去地点 JSON 数组' AFTER `pace`,
  ADD COLUMN `constraints_json` text DEFAULT NULL COMMENT '特殊约束 JSON' AFTER `must_visit_json`,
  ADD COLUMN `daily_start_time` time DEFAULT NULL COMMENT '每日开始时间' AFTER `constraints_json`,
  ADD COLUMN `daily_end_time` time DEFAULT NULL COMMENT '每日结束时间' AFTER `daily_start_time`,
  ADD COLUMN `overview_status` varchar(16) DEFAULT NULL COMMENT '行程总览状态' AFTER `daily_end_time`,
  ADD COLUMN `overview_skeleton` varchar(500) DEFAULT NULL COMMENT '行程总览骨架' AFTER `overview_status`,
  ADD COLUMN `overview_detail` varchar(1000) DEFAULT NULL COMMENT '行程总览详情' AFTER `overview_skeleton`,
  ADD COLUMN `planner_type` varchar(32) DEFAULT NULL COMMENT '规划器类型' AFTER `overview_detail`,
  ADD COLUMN `planner_validation` varchar(32) DEFAULT NULL COMMENT '规划校验状态' AFTER `planner_type`,
  ADD COLUMN `macro_skeleton_json` longtext DEFAULT NULL COMMENT '托管 Agent 宏观行程快照' AFTER `planner_validation`,
  ADD COLUMN `citation_ids_json` text DEFAULT NULL COMMENT '行程引用ID JSON 数组' AFTER `macro_skeleton_json`,
  ADD UNIQUE KEY `uk_trip_itinerary_id` (`tenant_id`, `trip_itinerary_id`),
  ADD KEY `idx_member_start_date` (`tenant_id`, `member_id`, `start_date`),
  ADD KEY `idx_trip_version` (`tenant_id`, `trip_id`, `version`);

CREATE TABLE `gift_user_itinerary_day` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `user_itinerary_id` bigint NOT NULL COMMENT '用户行程ID',
  `day` int NOT NULL COMMENT '第几天，从1开始',
  `date` date DEFAULT NULL COMMENT '行程日期',
  `province_id` int DEFAULT NULL COMMENT '省级地区ID',
  `city_id` int DEFAULT NULL COMMENT '城市ID',
  `district_id` int DEFAULT NULL COMMENT '区县ID',
  `city` varchar(128) DEFAULT NULL COMMENT '城市名称',
  `area` varchar(128) DEFAULT NULL COMMENT '当日活动区域名称',
  `theme` varchar(256) DEFAULT NULL COMMENT '当日主题',
  `anchor_poi_names_json` text DEFAULT NULL COMMENT '锚点地点名称 JSON 数组',
  `sort` int NOT NULL DEFAULT 0 COMMENT '排序',
  `overview_status` varchar(16) DEFAULT NULL COMMENT '每日总览状态',
  `overview_skeleton` varchar(500) DEFAULT NULL COMMENT '每日总览骨架',
  `overview_detail` varchar(1000) DEFAULT NULL COMMENT '每日总览详情',
  `planner` varchar(32) DEFAULT NULL COMMENT '日内排程器',
  `planning_status` varchar(16) DEFAULT NULL COMMENT '日内排程状态',
  `macro_source` varchar(32) DEFAULT NULL COMMENT '宏观规划来源',
  `selection_status` varchar(16) DEFAULT NULL COMMENT '候选选择状态',
  `route_data_status` varchar(16) DEFAULT NULL COMMENT '路线数据状态',
  `budget_status` varchar(16) DEFAULT NULL COMMENT '预算约束状态',
  `requested_scenic_count` int DEFAULT NULL COMMENT '请求安排的景点数',
  `selected_scenic_count` int DEFAULT NULL COMMENT '实际安排的景点数',
  `day_start_time` time DEFAULT NULL COMMENT '当日开始时间',
  `day_end_time` time DEFAULT NULL COMMENT '当日结束时间',
  `dropped_node_ids_json` text DEFAULT NULL COMMENT '未选节点ID JSON 数组',
  `candidate_counts_json` text DEFAULT NULL COMMENT '候选数量 JSON',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人编号',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人编号',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_itinerary_day` (`tenant_id`, `user_itinerary_id`, `day`),
  KEY `idx_user_itinerary_sort` (`tenant_id`, `user_itinerary_id`, `sort`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户行程每日安排';

CREATE TABLE `gift_user_itinerary_item` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `user_itinerary_id` bigint NOT NULL COMMENT '用户行程ID',
  `user_itinerary_day_id` bigint DEFAULT NULL COMMENT '用户行程每日安排ID；到达和返程节点为空',
  `item_id` varchar(64) DEFAULT NULL COMMENT '行程版本内稳定节点ID',
  `day` int NOT NULL COMMENT '第几天；到达和返程节点为0',
  `type` varchar(16) DEFAULT NULL COMMENT '节点类型：ACTIVITY/MEAL/LODGING/TRANSPORT',
  `slot` varchar(32) NOT NULL COMMENT '节点时段或角色',
  `label` varchar(32) DEFAULT NULL COMMENT '节点展示名称',
  `sort` int NOT NULL DEFAULT 0 COMMENT '当日排序',
  `start_time` time DEFAULT NULL COMMENT '开始时间',
  `end_time` time DEFAULT NULL COMMENT '结束时间',
  `duration_minutes` int DEFAULT NULL COMMENT '计划停留时长，分钟',
  `suggested_stay_minutes` int DEFAULT NULL COMMENT '建议停留时长，分钟',
  `buffer_minutes_after` int DEFAULT NULL COMMENT '节点后缓冲时长，分钟',
  `travel_minutes_from_previous` int DEFAULT NULL COMMENT '从上一节点出发的交通时长，分钟',
  `poi_id` varchar(64) DEFAULT NULL COMMENT '高德 POI ID',
  `poi_name` varchar(256) DEFAULT NULL COMMENT 'POI 名称',
  `province_id` int DEFAULT NULL COMMENT '省级地区ID',
  `city_id` int DEFAULT NULL COMMENT '城市ID',
  `district_id` int DEFAULT NULL COMMENT '区县ID',
  `city` varchar(128) DEFAULT NULL COMMENT '城市名称',
  `area` varchar(128) DEFAULT NULL COMMENT '活动区域名称',
  `address_detail` varchar(512) DEFAULT NULL COMMENT '详细地址',
  `longitude` decimal(10,7) DEFAULT NULL COMMENT '经度',
  `latitude` decimal(10,7) DEFAULT NULL COMMENT '纬度',
  `coordinate_system` varchar(16) DEFAULT NULL COMMENT '坐标系，当前为 GCJ02',
  `business_hours` varchar(256) DEFAULT NULL COMMENT '营业时间',
  `phone_no` varchar(64) DEFAULT NULL COMMENT '联系电话',
  `cover_url` varchar(1024) DEFAULT NULL COMMENT '封面图',
  `rating` decimal(4,2) DEFAULT NULL COMMENT '评分',
  `cost` decimal(12,2) DEFAULT NULL COMMENT '预估费用，单位元',
  `tags_json` text DEFAULT NULL COMMENT '标签 JSON',
  `skeleton` varchar(500) DEFAULT NULL COMMENT '节点骨架文案',
  `detail` varchar(1000) DEFAULT NULL COMMENT '节点补全详情',
  `status` varchar(16) NOT NULL DEFAULT 'PENDING' COMMENT '节点状态：PENDING/RESOLVED/FAILED',
  `resolve_status` tinyint NOT NULL DEFAULT 0 COMMENT '补全状态：0待处理 1处理中 2已完成 3失败',
  `route_status` varchar(16) DEFAULT NULL COMMENT '到达本节点的路线状态',
  `planning_status` varchar(16) DEFAULT NULL COMMENT '排程校验状态',
  `poi_verification_status` varchar(16) DEFAULT NULL COMMENT 'POI 核验状态',
  `utility_score` int DEFAULT NULL COMMENT '偏好效用分',
  `must_visit` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否必去',
  `locked` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否锁定',
  `source` varchar(32) DEFAULT NULL COMMENT '节点规划来源',
  `provider` varchar(32) DEFAULT NULL COMMENT 'POI 数据提供方',
  `poi_snapshot_json` text DEFAULT NULL COMMENT 'POI 原始核验快照',
  `candidates_json` text DEFAULT NULL COMMENT '候选地点 JSON',
  `citation_ids_json` text DEFAULT NULL COMMENT '引用ID JSON 数组',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人编号',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人编号',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_itinerary_item` (`tenant_id`, `user_itinerary_id`, `item_id`),
  KEY `idx_user_itinerary_day_sort` (`tenant_id`, `user_itinerary_id`, `day`, `sort`),
  KEY `idx_poi_id` (`tenant_id`, `poi_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户行程节点';

CREATE TABLE `gift_user_itinerary_transport_segment` (
  `id` bigint NOT NULL AUTO_INCREMENT COMMENT '主键',
  `tenant_id` bigint NOT NULL COMMENT '租户ID',
  `user_itinerary_id` bigint NOT NULL COMMENT '用户行程ID',
  `user_itinerary_day_id` bigint NOT NULL COMMENT '用户行程每日安排ID',
  `day` int NOT NULL COMMENT '第几天',
  `sort` int NOT NULL DEFAULT 0 COMMENT '当日交通段排序',
  `from_item_id` varchar(64) DEFAULT NULL COMMENT '起点节点ID',
  `from_poi_id` varchar(64) DEFAULT NULL COMMENT '起点 POI ID',
  `from_poi_name` varchar(256) DEFAULT NULL COMMENT '起点名称',
  `from_longitude` decimal(10,7) DEFAULT NULL COMMENT '起点经度',
  `from_latitude` decimal(10,7) DEFAULT NULL COMMENT '起点纬度',
  `to_item_id` varchar(64) DEFAULT NULL COMMENT '终点节点ID',
  `to_poi_id` varchar(64) DEFAULT NULL COMMENT '终点 POI ID',
  `to_poi_name` varchar(256) DEFAULT NULL COMMENT '终点名称',
  `to_longitude` decimal(10,7) DEFAULT NULL COMMENT '终点经度',
  `to_latitude` decimal(10,7) DEFAULT NULL COMMENT '终点纬度',
  `coordinate_system` varchar(16) NOT NULL DEFAULT 'GCJ02' COMMENT '坐标系',
  `mode` varchar(16) DEFAULT NULL COMMENT '交通方式',
  `distance_meters` bigint DEFAULT NULL COMMENT '距离，米',
  `duration_minutes` int DEFAULT NULL COMMENT '时长，分钟',
  `provider` varchar(32) DEFAULT NULL COMMENT '路线数据提供方',
  `status` varchar(16) DEFAULT NULL COMMENT '路线状态：VERIFIED/ESTIMATED/PENDING',
  `route_points_json` longtext DEFAULT NULL COMMENT '路线轨迹点 JSON',
  `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建人编号',
  `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新人编号',
  `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除',
  PRIMARY KEY (`id`),
  UNIQUE KEY `uk_user_itinerary_day_sort` (`tenant_id`, `user_itinerary_id`, `day`, `sort`),
  KEY `idx_user_itinerary_day` (`tenant_id`, `user_itinerary_day_id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='用户行程交通段';
