-- 已部署行程表字段备注补齐脚本，供数据库代码生成读取字段描述。
-- 仅修改字段定义中的 COMMENT，不调整索引，不迁移或删除业务数据。

ALTER TABLE `gift_itinerary`
  MODIFY COLUMN `next_city_id` int DEFAULT NULL COMMENT '第二城市ID';

ALTER TABLE `gift_itinerary_day`
  MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '通用行程日程ID',
  MODIFY COLUMN `itinerary_id` bigint NOT NULL COMMENT '通用行程ID',
  MODIFY COLUMN `day` int NOT NULL COMMENT '行程第几天，从1开始',
  MODIFY COLUMN `city_id` int DEFAULT NULL COMMENT '当日城市ID',
  MODIFY COLUMN `district_id` int DEFAULT NULL COMMENT '当日区县ID',
  MODIFY COLUMN `title` varchar(128) DEFAULT NULL COMMENT '当日标题',
  MODIFY COLUMN `description` varchar(1000) DEFAULT NULL COMMENT '当日描述',
  MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值',
  MODIFY COLUMN `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  MODIFY COLUMN `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新者',
  MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除';

ALTER TABLE `gift_user_itinerary_conversation_event`
  MODIFY COLUMN `tenant_id` bigint NOT NULL COMMENT '租户ID',
  MODIFY COLUMN `conversation_id` bigint NOT NULL COMMENT '用户行程会话ID',
  MODIFY COLUMN `reply_event_id` bigint DEFAULT NULL COMMENT '回复的事件ID',
  MODIFY COLUMN `user_itinerary_id` bigint DEFAULT NULL COMMENT '关联的用户行程ID',
  MODIFY COLUMN `role` varchar(16) DEFAULT NULL COMMENT '消息角色',
  MODIFY COLUMN `stage` varchar(32) DEFAULT NULL COMMENT '行程处理阶段',
  MODIFY COLUMN `content` text DEFAULT NULL COMMENT '事件文本内容',
  MODIFY COLUMN `payload_json` longtext DEFAULT NULL COMMENT '事件扩展数据JSON',
  MODIFY COLUMN `status` tinyint NOT NULL DEFAULT 1 COMMENT '事件状态',
  MODIFY COLUMN `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新者',
  MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除';

ALTER TABLE `gift_itinerary_day_item`
  MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '通用行程节点ID',
  MODIFY COLUMN `itinerary_id` bigint NOT NULL COMMENT '通用行程ID',
  MODIFY COLUMN `itinerary_day_id` bigint NOT NULL COMMENT '通用行程日程ID',
  MODIFY COLUMN `type` varchar(16) NOT NULL DEFAULT 'ACTIVITY' COMMENT '节点类型',
  MODIFY COLUMN `slot` varchar(32) DEFAULT NULL COMMENT '节点时段',
  MODIFY COLUMN `title` varchar(128) NOT NULL COMMENT '节点标题',
  MODIFY COLUMN `sub_title` varchar(128) DEFAULT NULL COMMENT '节点副标题',
  MODIFY COLUMN `description` varchar(1024) NOT NULL DEFAULT '' COMMENT '节点描述',
  MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '当日节点排序值',
  MODIFY COLUMN `start_time` time DEFAULT NULL COMMENT '计划开始时间',
  MODIFY COLUMN `duration_minutes` int DEFAULT NULL COMMENT '建议停留分钟数',
  MODIFY COLUMN `poi_id` varchar(64) DEFAULT NULL COMMENT 'POI供应商地点ID',
  MODIFY COLUMN `province_id` int DEFAULT NULL COMMENT 'POI省级区域ID',
  MODIFY COLUMN `city_id` int DEFAULT NULL COMMENT 'POI城市ID',
  MODIFY COLUMN `district_id` int DEFAULT NULL COMMENT 'POI区县ID',
  MODIFY COLUMN `longitude` decimal(10,7) DEFAULT NULL COMMENT 'POI经度',
  MODIFY COLUMN `latitude` decimal(10,7) DEFAULT NULL COMMENT 'POI纬度',
  MODIFY COLUMN `cover_url` varchar(1024) DEFAULT NULL COMMENT '封面图地址',
  MODIFY COLUMN `cover_width` int DEFAULT NULL COMMENT '封面图宽度',
  MODIFY COLUMN `cover_height` int DEFAULT NULL COMMENT '封面图高度',
  MODIFY COLUMN `pic_urls` text DEFAULT NULL COMMENT '图片地址集合',
  MODIFY COLUMN `pic_sizes` text DEFAULT NULL COMMENT '图片尺寸集合',
  MODIFY COLUMN `tags` text DEFAULT NULL COMMENT '标签集合',
  MODIFY COLUMN `gd_position` varchar(128) DEFAULT NULL COMMENT '高德地图坐标',
  MODIFY COLUMN `business_time` varchar(128) DEFAULT NULL COMMENT '营业时间',
  MODIFY COLUMN `address_detail` varchar(512) DEFAULT NULL COMMENT '详细地址',
  MODIFY COLUMN `phone_no` varchar(64) DEFAULT NULL COMMENT '联系电话',
  MODIFY COLUMN `tenant_id` bigint NOT NULL DEFAULT 1 COMMENT '租户ID',
  MODIFY COLUMN `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新者',
  MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除';

ALTER TABLE `gift_user_itinerary`
  MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户行程ID',
  MODIFY COLUMN `conversation_id` bigint NOT NULL COMMENT '用户行程会话ID',
  MODIFY COLUMN `member_id` bigint NOT NULL COMMENT '会员ID',
  MODIFY COLUMN `request_event_id` bigint DEFAULT NULL COMMENT '触发行程生成的请求事件ID',
  MODIFY COLUMN `result_event_id` bigint DEFAULT NULL COMMENT '行程生成结果事件ID',
  MODIFY COLUMN `status` tinyint NOT NULL DEFAULT 1 COMMENT '行程状态',
  MODIFY COLUMN `title` varchar(128) NOT NULL COMMENT '行程标题',
  MODIFY COLUMN `cover_url` varchar(1024) NOT NULL DEFAULT '' COMMENT '封面图地址',
  MODIFY COLUMN `cover_width` int NOT NULL DEFAULT 0 COMMENT '封面图宽度',
  MODIFY COLUMN `cover_height` int NOT NULL DEFAULT 0 COMMENT '封面图高度',
  MODIFY COLUMN `start_date` date DEFAULT NULL COMMENT '出发日期',
  MODIFY COLUMN `end_date` date DEFAULT NULL COMMENT '结束日期',
  MODIFY COLUMN `day_cnt` int NOT NULL DEFAULT 0 COMMENT '行程天数',
  MODIFY COLUMN `departure` varchar(128) DEFAULT NULL COMMENT '出发地',
  MODIFY COLUMN `destination` varchar(128) DEFAULT NULL COMMENT '目的地',
  MODIFY COLUMN `traveler_count` int DEFAULT NULL COMMENT '出行人数',
  MODIFY COLUMN `budget` int DEFAULT NULL COMMENT '行程总预算，不含往返交通',
  MODIFY COLUMN `hotel_budget` int DEFAULT NULL COMMENT '住宿预算',
  MODIFY COLUMN `traveler_profile_json` text DEFAULT NULL COMMENT '出行人画像JSON',
  MODIFY COLUMN `interests_json` text DEFAULT NULL COMMENT '兴趣偏好JSON',
  MODIFY COLUMN `pace` varchar(32) DEFAULT NULL COMMENT '行程节奏',
  MODIFY COLUMN `must_visit_json` text DEFAULT NULL COMMENT '必去地点JSON',
  MODIFY COLUMN `constraints_json` text DEFAULT NULL COMMENT '行程约束JSON',
  MODIFY COLUMN `daily_start_time` time DEFAULT NULL COMMENT '每日开始时间',
  MODIFY COLUMN `daily_end_time` time DEFAULT NULL COMMENT '每日结束时间',
  MODIFY COLUMN `overview_status` varchar(16) DEFAULT NULL COMMENT '行程总览生成状态',
  MODIFY COLUMN `overview_skeleton` varchar(500) DEFAULT NULL COMMENT '行程总览骨架文案',
  MODIFY COLUMN `overview_detail` varchar(1000) DEFAULT NULL COMMENT '行程总览详细文案',
  MODIFY COLUMN `planner_type` varchar(32) DEFAULT NULL COMMENT '规划器类型',
  MODIFY COLUMN `planner_validation` varchar(32) DEFAULT NULL COMMENT '规划结果校验状态',
  MODIFY COLUMN `tenant_id` bigint NOT NULL COMMENT '租户ID',
  MODIFY COLUMN `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新者',
  MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除';

ALTER TABLE `gift_user_itinerary_conversation`
  MODIFY COLUMN `title` varchar(128) NOT NULL DEFAULT '新旅行计划' COMMENT '会话标题',
  MODIFY COLUMN `pinned` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否置顶',
  MODIFY COLUMN `province_id` bigint DEFAULT NULL COMMENT '目的地省级区域ID',
  MODIFY COLUMN `city_id` bigint DEFAULT NULL COMMENT '目的地城市ID',
  MODIFY COLUMN `district_id` bigint DEFAULT NULL COMMENT '目的地区县ID',
  MODIFY COLUMN `intake_agent_session_id` varchar(64) DEFAULT NULL COMMENT '信息收集 Agent 会话ID',
  MODIFY COLUMN `plan_agent_session_id` varchar(64) DEFAULT NULL COMMENT '行程生成 Agent 会话ID',
  MODIFY COLUMN `state_json` text NOT NULL COMMENT '已采集的行程需求状态JSON',
  MODIFY COLUMN `missing_required_json` text NOT NULL COMMENT '尚未补齐的必填字段JSON',
  MODIFY COLUMN `status` tinyint NOT NULL DEFAULT 1 COMMENT '会话状态',
  MODIFY COLUMN `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新者',
  MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除';

ALTER TABLE `gift_user_itinerary_day`
  MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户行程日程ID',
  MODIFY COLUMN `user_itinerary_id` bigint NOT NULL COMMENT '用户行程ID',
  MODIFY COLUMN `day` int NOT NULL COMMENT '行程第几天，从1开始',
  MODIFY COLUMN `date` date DEFAULT NULL COMMENT '行程日期',
  MODIFY COLUMN `province_id` int DEFAULT NULL COMMENT '当日省级区域ID',
  MODIFY COLUMN `city_id` int DEFAULT NULL COMMENT '当日城市ID',
  MODIFY COLUMN `district_id` int DEFAULT NULL COMMENT '当日区县ID',
  MODIFY COLUMN `city` varchar(128) DEFAULT NULL COMMENT '当日城市名称',
  MODIFY COLUMN `area` varchar(128) DEFAULT NULL COMMENT '当日游玩区域',
  MODIFY COLUMN `theme` varchar(256) DEFAULT NULL COMMENT '当日行程主题',
  MODIFY COLUMN `anchor_poi_names_json` text DEFAULT NULL COMMENT '当日锚点POI名称JSON',
  MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '排序值',
  MODIFY COLUMN `overview_status` varchar(16) DEFAULT NULL COMMENT '每日总览生成状态',
  MODIFY COLUMN `overview_skeleton` varchar(500) DEFAULT NULL COMMENT '每日总览骨架文案',
  MODIFY COLUMN `overview_detail` varchar(1000) DEFAULT NULL COMMENT '每日总览详细文案',
  MODIFY COLUMN `planner` varchar(32) DEFAULT NULL COMMENT '当日规划器',
  MODIFY COLUMN `planning_status` varchar(16) DEFAULT NULL COMMENT '当日排程状态',
  MODIFY COLUMN `macro_source` varchar(32) DEFAULT NULL COMMENT '宏观路线来源',
  MODIFY COLUMN `selection_status` varchar(16) DEFAULT NULL COMMENT '景点选择状态',
  MODIFY COLUMN `budget_status` varchar(16) DEFAULT NULL COMMENT '预算校验状态',
  MODIFY COLUMN `requested_scenic_count` int DEFAULT NULL COMMENT '期望景点数量',
  MODIFY COLUMN `selected_scenic_count` int DEFAULT NULL COMMENT '实际选择景点数量',
  MODIFY COLUMN `day_start_time` time DEFAULT NULL COMMENT '当日开始时间',
  MODIFY COLUMN `day_end_time` time DEFAULT NULL COMMENT '当日结束时间',
  MODIFY COLUMN `dropped_node_ids_json` text DEFAULT NULL COMMENT '排程丢弃的节点ID JSON',
  MODIFY COLUMN `candidate_counts_json` text DEFAULT NULL COMMENT '各类候选数量JSON',
  MODIFY COLUMN `tenant_id` bigint NOT NULL COMMENT '租户ID',
  MODIFY COLUMN `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新者',
  MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除';

ALTER TABLE `gift_user_itinerary_day_item`
  MODIFY COLUMN `id` bigint NOT NULL AUTO_INCREMENT COMMENT '用户行程节点记录ID',
  MODIFY COLUMN `user_itinerary_id` bigint NOT NULL COMMENT '用户行程ID',
  MODIFY COLUMN `user_itinerary_day_id` bigint NOT NULL COMMENT '用户行程日程ID',
  MODIFY COLUMN `item_id` varchar(64) NOT NULL COMMENT '行程节点业务ID',
  MODIFY COLUMN `day` int NOT NULL COMMENT '所属行程天数',
  MODIFY COLUMN `type` varchar(16) NOT NULL COMMENT '节点类型',
  MODIFY COLUMN `slot` varchar(32) NOT NULL COMMENT '节点时段',
  MODIFY COLUMN `label` varchar(32) DEFAULT NULL COMMENT '节点展示标签',
  MODIFY COLUMN `sort` int NOT NULL DEFAULT 0 COMMENT '当日节点排序值',
  MODIFY COLUMN `start_time` time DEFAULT NULL COMMENT '计划开始时间',
  MODIFY COLUMN `end_time` time DEFAULT NULL COMMENT '计划结束时间',
  MODIFY COLUMN `duration_minutes` int DEFAULT NULL COMMENT '建议停留分钟数',
  MODIFY COLUMN `poi_id` varchar(64) DEFAULT NULL COMMENT 'POI供应商地点ID',
  MODIFY COLUMN `poi_name` varchar(256) DEFAULT NULL COMMENT 'POI名称',
  MODIFY COLUMN `province_id` int DEFAULT NULL COMMENT 'POI省级区域ID',
  MODIFY COLUMN `city_id` int DEFAULT NULL COMMENT 'POI城市ID',
  MODIFY COLUMN `district_id` int DEFAULT NULL COMMENT 'POI区县ID',
  MODIFY COLUMN `city` varchar(128) DEFAULT NULL COMMENT 'POI城市名称',
  MODIFY COLUMN `area` varchar(128) DEFAULT NULL COMMENT 'POI所在区域',
  MODIFY COLUMN `address_detail` varchar(512) DEFAULT NULL COMMENT 'POI详细地址',
  MODIFY COLUMN `longitude` decimal(10,7) DEFAULT NULL COMMENT 'POI经度',
  MODIFY COLUMN `latitude` decimal(10,7) DEFAULT NULL COMMENT 'POI纬度',
  MODIFY COLUMN `coordinate_system` varchar(16) DEFAULT NULL COMMENT '坐标系',
  MODIFY COLUMN `business_hours` varchar(256) DEFAULT NULL COMMENT '营业时间',
  MODIFY COLUMN `phone_no` varchar(64) DEFAULT NULL COMMENT '联系电话',
  MODIFY COLUMN `cover_url` varchar(1024) DEFAULT NULL COMMENT '封面图地址',
  MODIFY COLUMN `rating` decimal(4,2) DEFAULT NULL COMMENT '评分',
  MODIFY COLUMN `cost` decimal(12,2) DEFAULT NULL COMMENT '预计花费',
  MODIFY COLUMN `tags_json` text DEFAULT NULL COMMENT '标签JSON',
  MODIFY COLUMN `skeleton` varchar(500) DEFAULT NULL COMMENT '节点骨架文案',
  MODIFY COLUMN `detail` varchar(1000) DEFAULT NULL COMMENT '节点详细文案',
  MODIFY COLUMN `status` varchar(16) NOT NULL DEFAULT 'PENDING' COMMENT '节点内容状态',
  MODIFY COLUMN `resolve_status` tinyint NOT NULL DEFAULT 0 COMMENT '节点解析状态',
  MODIFY COLUMN `planning_status` varchar(16) DEFAULT NULL COMMENT '节点排程状态',
  MODIFY COLUMN `poi_verification_status` varchar(16) DEFAULT NULL COMMENT 'POI校验状态',
  MODIFY COLUMN `must_visit` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否必去',
  MODIFY COLUMN `locked` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否锁定',
  MODIFY COLUMN `source` varchar(32) DEFAULT NULL COMMENT '节点来源',
  MODIFY COLUMN `provider` varchar(32) DEFAULT NULL COMMENT 'POI数据供应商',
  MODIFY COLUMN `poi_snapshot_json` text DEFAULT NULL COMMENT 'POI快照JSON',
  MODIFY COLUMN `candidates_json` text DEFAULT NULL COMMENT '候选POI JSON',
  MODIFY COLUMN `citation_ids_json` text DEFAULT NULL COMMENT '引用来源ID JSON',
  MODIFY COLUMN `tenant_id` bigint NOT NULL COMMENT '租户ID',
  MODIFY COLUMN `creator` varchar(64) NOT NULL DEFAULT '' COMMENT '创建者',
  MODIFY COLUMN `create_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  MODIFY COLUMN `updater` varchar(64) NOT NULL DEFAULT '' COMMENT '更新者',
  MODIFY COLUMN `update_time` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  MODIFY COLUMN `deleted` bit(1) NOT NULL DEFAULT b'0' COMMENT '是否删除';
